const goals = [
  "Build a research agent",
  "Develop an autonomous indexing bot",
  "Create a scalable data miner",
  "Launch a next-gen trading executor",
  "Deploy an intelligent governance tool",
  "Design a decentralized proposal analyzer",
  "Engineer a context-aware workflow assistant",
  "Build a contract verifier",
  "Develop an autonomous security scanner",
  "Create a scalable task orchestrator",
  "Launch a next-gen risk forecaster",
  "Deploy an intelligent metadata agent",
  "Design a decentralized wallet router",
  "Engineer a context-aware multi-agent coordinator",
  "Build a dataset builder",
  "Develop an autonomous AI prompt enhancer",
  "Create a scalable signal aggregator",
  "Launch a next-gen automation agent",
  "Deploy an intelligent model tester",
  "Design a decentralized insight generator",
  "Engineer a context-aware research agent",
  "Build a indexing bot",
  "Develop an autonomous data miner",
  "Create a scalable trading executor",
  "Launch a next-gen governance tool",
  "Deploy an intelligent proposal analyzer",
  "Design a decentralized workflow assistant",
  "Engineer a context-aware contract verifier",
  "Build a security scanner",
  "Develop an autonomous task orchestrator",
  "Create a scalable risk forecaster",
  "Launch a next-gen metadata agent",
  "Deploy an intelligent wallet router",
  "Design a decentralized multi-agent coordinator",
  "Engineer a context-aware dataset builder",
  "Build a AI prompt enhancer",
  "Develop an autonomous signal aggregator",
  "Create a scalable automation agent",
  "Launch a next-gen model tester",
  "Deploy an intelligent insight generator",
  "Design a decentralized research agent",
  "Engineer a context-aware indexing bot",
  "Build a data miner",
  "Develop an autonomous trading executor",
  "Create a scalable governance tool",
  "Launch a next-gen proposal analyzer",
  "Deploy an intelligent workflow assistant",
  "Design a decentralized contract verifier",
  "Engineer a context-aware security scanner",
  "Build a task orchestrator",
  "Develop an autonomous risk forecaster",
  "Create a scalable metadata agent",
  "Launch a next-gen wallet router",
  "Deploy an intelligent multi-agent coordinator",
  "Design a decentralized dataset builder",
  "Engineer a context-aware AI prompt enhancer",
  "Build a signal aggregator",
  "Develop an autonomous automation agent",
  "Create a scalable model tester",
  "Launch a next-gen insight generator",
  "Deploy an intelligent research agent",
  "Design a decentralized indexing bot",
  "Engineer a context-aware data miner",
  "Build a trading executor",
  "Develop an autonomous governance tool",
  "Create a scalable proposal analyzer",
  "Launch a next-gen workflow assistant",
  "Deploy an intelligent contract verifier",
  "Design a decentralized security scanner",
  "Engineer a context-aware task orchestrator",
  "Build a risk forecaster",
  "Develop an autonomous metadata agent",
  "Create a scalable wallet router",
  "Launch a next-gen multi-agent coordinator",
  "Deploy an intelligent dataset builder",
  "Design a decentralized AI prompt enhancer",
  "Engineer a context-aware signal aggregator",
  "Build a automation agent",
  "Develop an autonomous model tester",
  "Create a scalable insight generator",
  "Launch a next-gen research agent",
  "Deploy an intelligent indexing bot",
  "Design a decentralized data miner",
  "Engineer a context-aware trading executor",
  "Build a governance tool",
  "Develop an autonomous proposal analyzer",
  "Create a scalable workflow assistant",
  "Launch a next-gen contract verifier",
  "Deploy an intelligent security scanner",
  "Design a decentralized task orchestrator",
  "Engineer a context-aware risk forecaster",
  "Build a metadata agent",
  "Develop an autonomous wallet router",
  "Create a scalable multi-agent coordinator",
  "Launch a next-gen dataset builder",
  "Deploy an intelligent AI prompt enhancer",
  "Design a decentralized signal aggregator",
  "Engineer a context-aware automation agent",
  "Build a model tester",
  "Develop an autonomous insight generator",
  "Create a scalable research agent",
  "Launch a next-gen indexing bot",
  "Deploy an intelligent data miner",
  "Design a decentralized trading executor",
  "Engineer a context-aware governance tool",
  "Build a proposal analyzer",
  "Develop an autonomous workflow assistant",
  "Create a scalable contract verifier",
  "Launch a next-gen security scanner",
  "Deploy an intelligent task orchestrator",
  "Design a decentralized risk forecaster",
  "Engineer a context-aware metadata agent",
  "Build a wallet router",
  "Develop an autonomous multi-agent coordinator",
  "Create a scalable dataset builder",
  "Launch a next-gen AI prompt enhancer",
  "Deploy an intelligent signal aggregator",
  "Design a decentralized automation agent",
  "Engineer a context-aware model tester",
  "Build a insight generator",
  "Develop an autonomous research agent",
  "Create a scalable indexing bot",
  "Launch a next-gen data miner",
  "Deploy an intelligent trading executor",
  "Design a decentralized governance tool",
  "Engineer a context-aware proposal analyzer",
  "Build a workflow assistant",
  "Develop an autonomous contract verifier",
  "Create a scalable security scanner",
  "Launch a next-gen task orchestrator",
  "Deploy an intelligent risk forecaster",
  "Design a decentralized metadata agent",
  "Engineer a context-aware wallet router",
  "Build a multi-agent coordinator",
  "Develop an autonomous dataset builder",
  "Create a scalable AI prompt enhancer",
  "Launch a next-gen signal aggregator",
  "Deploy an intelligent automation agent",
  "Design a decentralized model tester",
  "Engineer a context-aware insight generator",
];
const targets = [
  "Designed for DAOs",
  "Customized for DeFi protocols",
  "Tailored for NFT marketplaces",
  "Optimized for zk-rollups",
  "Integrated for Web3 builders",
  "Engineered for L2 validators",
  "Built for decentralized research",
  "Designed for crypto educators",
  "Customized for protocol governors",
  "Tailored for on-chain treasuries",
  "Optimized for crypto assets",
  "Integrated for decentralized identity systems",
  "Engineered for smart contract auditing",
  "Built for cross-chain interoperability",
  "Designed for privacy-preserving applications",
  "Customized for decentralized exchanges",
  "Tailored for Web3 content creators",
  "Optimized for community-driven projects",
  "Integrated for decentralized finance",
  "Engineered for Web3 data analytics",
  "Built for autonomous agents",
  "Designed for decentralized governance",
  "Customized for blockchain-based games",
  "Tailored for tokenized assets",
  "Optimized for NFT platforms",
  "Integrated for decentralized marketplaces",
  "Engineered for staking mechanisms",
  "Built for decentralized file storage",
  "Designed for DAO treasury management",
  "Customized for decentralized social media",
  "Tailored for crypto wallets",
  "Optimized for blockchain scalability",
  "Integrated for Layer 1 ecosystems",
  "Engineered for decentralized oracles",
  "Built for Web3 privacy tools",
  "Designed for metaverse applications",
  "Customized for decentralized infrastructure",
  "Tailored for decentralized communication systems",
  "Optimized for blockchain explorers",
  "Integrated for decentralized voting systems",
  "Engineered for decentralized prediction markets",
  "Built for decentralized autonomous organizations",
  "Designed for crypto asset management",
  "Customized for decentralized insurance",
  "Tailored for decentralized logistics",
  "Optimized for Web3 supply chains",
  "Integrated for decentralized cloud storage",
  "Engineered for blockchain-based education systems",
  "Built for decentralized health solutions",
  "Designed for tokenized real estate",
  "Customized for Web3 identity verification",
  "Tailored for decentralized cloud computing",
  "Optimized for decentralized payment systems",
  "Integrated for smart contract automation",
  "Engineered for decentralized lending platforms",
  "Built for decentralized data marketplaces",
  "Designed for Web3 content monetization",
  "Customized for crypto tax reporting",
  "Tailored for blockchain voting systems",
  "Optimized for decentralized crowdfunding",
  "Integrated for decentralized video streaming",
  "Engineered for decentralized asset tracking",
  "Built for decentralized job markets",
  "Designed for Web3 intellectual property protection",
  "Customized for blockchain-based supply chains",
  "Tailored for decentralized finance tools",
  "Optimized for decentralized project management",
  "Integrated for decentralized AI services",
  "Engineered for Web3 mobile apps",
  "Built for tokenized community governance",
  "Designed for decentralized data encryption",
  "Customized for Web3 cross-platform integration",
  "Tailored for decentralized collaborative workspaces",
  "Optimized for blockchain-based certifications",
  "Integrated for Web3 marketplace frameworks",
  "Engineered for decentralized music streaming",
  "Built for decentralized art platforms",
  "Designed for decentralized publishing",
  "Customized for decentralized healthcare systems",
  "Tailored for Web3 supply chain transparency",
  "Optimized for blockchain-based lending",
  "Integrated for decentralized reputation systems",
  "Engineered for decentralized gaming platforms",
  "Built for blockchain-based ticketing systems",
  "Designed for decentralized IoT networks",
  "Customized for Web3 finance applications",
  "Tailored for decentralized mobility solutions",
  "Optimized for decentralized intellectual property rights",
  "Integrated for blockchain-based voting mechanisms",
  "Engineered for decentralized energy grids",
  "Built for decentralized social networks",
  "Designed for Web3-based collaboration tools",
  "Customized for tokenized real estate investments",
  "Tailored for decentralized art marketplaces",
  "Optimized for decentralized personal finance management",
  "Integrated for Web3 investment platforms",
  "Engineered for decentralized scientific research",
  "Built for blockchain-based legal systems",
  "Designed for decentralized trade finance",
  "Customized for decentralized cloud infrastructures",
  "Tailored for Web3 reputation management systems",
  "Optimized for decentralized IPFS networks",
  "Integrated for blockchain-powered microservices",
  "Engineered for decentralized autonomous logistics",
  "Built for Web3-based peer-to-peer lending",
  "Designed for decentralized content distribution",
  "Customized for decentralized hardware protocols",
  "Tailored for Web3-based asset tokenization",
  "Optimized for decentralized cooperative models",
  "Integrated for decentralized ownership structures",
  "Engineered for decentralized supply chain verification",
  "Built for decentralized open-source software ecosystems",
  "Designed for decentralized asset custody",
  "Customized for blockchain-powered digital rights management",
  "Tailored for decentralized global payment systems",
  "Optimized for blockchain-based supply chain financing",
  "Integrated for decentralized credit scoring",
  "Engineered for Web3-based legal agreements",
  "Built for decentralized credit markets",
  "Designed for decentralized dispute resolution",
  "Customized for decentralized knowledge sharing",
  "Tailored for blockchain-based IP licensing",
  "Optimized for Web3-based property management",
  "Integrated for decentralized online marketplaces",
  "Engineered for decentralized digital advertising",
  "Built for blockchain-based healthcare solutions",
  "Designed for decentralized legal frameworks",
  "Customized for decentralized content creation",
  "Tailored for decentralized data privacy",
  "Optimized for blockchain-based charity platforms",
  "Integrated for decentralized talent marketplaces",
  "Engineered for Web3-based auction platforms",
  "Built for decentralized capital markets",
  "Designed for decentralized crowdfunding platforms",
  "Customized for decentralized product distribution",
  "Tailored for blockchain-based tokenized ecosystems",
  "Optimized for decentralized education systems",
  "Integrated for Web3-based payment gateways",
  "Engineered for decentralized insurance protocols",
  "Built for decentralized reputation management",
  "Designed for decentralized knowledge-based platforms",
  "Customized for blockchain-powered content protection",
  "Tailored for decentralized community investment",
  "Optimized for decentralized cryptocurrency exchange",
  "Integrated for blockchain-based patent verification",
  "Engineered for decentralized environmental solutions",
  "Built for decentralized patent management systems",
  "Designed for decentralized gaming ecosystems",
  "Customized for Web3-based cross-border payments"
];
const techs = [
  "Ethereum",
  "Solana",
  "Polkadot",
  "Binance Smart Chain",
  "Layer 2 solutions",
  "zk-rollups",
  "Optimistic rollups",
  "IPFS",
  "Arweave",
  "Filecoin",
  "Web3.js",
  "Ethers.js",
  "Rust",
  "Go",
  "Python",
  "JavaScript",
  "TypeScript",
  "GraphQL",
  "MongoDB",
  "PostgreSQL",
  "MySQL",
  "Redis",
  "SQLite",
  "AWS Lambda",
  "Azure Functions",
  "Google Cloud Functions",
  "Docker",
  "Kubernetes",
  "Terraform",
  "Ansible",
  "CI/CD",
  "Jenkins",
  "Travis CI",
  "GitLab CI",
  "CircleCI",
  "Cloudflare",
  "NGINX",
  "Caddy",
  "Express.js",
  "NestJS",
  "React",
  "Vue.js",
  "Angular",
  "Svelte",
  "Next.js",
  "Nuxt.js",
  "Redux",
  "MobX",
  "Apollo Client",
  "React Query",
  "Tailwind CSS",
  "Bootstrap",
  "Material UI",
  "Foundation",
  "Ant Design",
  "Figma",
  "Sketch",
  "Adobe XD",
  "InVision",
  "Zeplin",
  "Python Flask",
  "Django",
  "FastAPI",
  "Spring Boot",
  "Node.js",
  "Golang",
  "Rust web frameworks",
  "Hyperledger",
  "Corda",
  "Cosmos SDK",
  "Cosmos Hub",
  "Tendermint",
  "Chainlink",
  "The Graph",
  "Uniswap",
  "SushiSwap",
  "Aave",
  "Compound",
  "MakerDAO",
  "Balancer",
  "Curve Finance",
  "Yearn Finance",
  "dYdX",
  "OpenZeppelin",
  "Hardhat",
  "Truffle",
  "Ethers.js",
  "Web3.py",
  "GraphQL API",
  "REST API",
  "SOAP API",
  "JSON-RPC",
  "WebSocket",
  "MQTT",
  "AMQP",
  "Pub/Sub",
  "Apache Kafka",
  "RabbitMQ",
  "Redis Streams",
  "Blockchain oracles",
  "Fantom",
  "Avalanche",
  "Polygon",
  "Tezos",
  "Algorand",
  "Cosmos",
  "EOS",
  "TRON",
  "Celo",
  "Lisk",
  "Flow",
  "Near Protocol",
  "StarkNet",
  "Immutable X",
  "Harmony",
  "Arbitrum",
  "Optimism",
  "zkSync",
  "Loopring",
  "Boba Network",
  "Moonbeam",
  "Moonriver",
  "zkPorter",
  "Aurora",
  "Kusama",
  "Acala",
  "Parallel Finance",
  "Manta Network",
  "Celo Dollar",
  "Frax Finance",
  "Terra",
  "Anchor Protocol",
  "Lido",
  "Rocket Pool",
  "Ethereum 2.0",
  "Chainlink VRF",
  "Chainlink Keepers",
  "Ethereum Name Service (ENS)",
  "Dune Analytics",
  "Flipside Crypto",
  "Quantstamp",
  "Tornado Cash",
  "Privacy-preserving cryptography",
  "Zero-knowledge proofs",
  "Homomorphic encryption",
  "Secure multiparty computation (SMC)",
  "Confidential computing",
  "Differential privacy",
  "Public key infrastructure (PKI)",
  "Tokenization",
  "Non-fungible tokens (NFTs)",
  "Decentralized finance (DeFi)",
  "Automated market makers (AMMs)",
  "Decentralized exchanges (DEXs)",
  "Token standards (ERC-20, ERC-721, ERC-1155)",
  "Decentralized autonomous organizations (DAOs)",
  "Staking mechanisms",
  "Governance tokens",
  "Flash loans",
  "Liquidity mining",
  "Yield farming",
  "Lending protocols",
  "Stablecoins",
  "Synthetic assets",
  "Decentralized oracles",
  "Cross-chain bridges",
  "Layer 1 blockchains",
  "Layer 2 scaling solutions",
  "Sidechains",
  "Interoperability protocols",
  "State channels",
  "Privacy coins",
  "Monero",
  "Zcash",
  "Dai",
  "Tether",
  "USD Coin",
  "Wrapped Bitcoin",
  "Synthetic assets",
  "Staking",
  "Delegated proof of stake (DPoS)",
  "Proof of work (PoW)",
  "Proof of stake (PoS)",
  "Proof of authority (PoA)",
  "Proof of history (PoH)",
  "Byzantine Fault Tolerance (BFT)",
  "Nervos Network",
  "Tendermint BFT",
  "Polkadot Relay Chain",
  "Substrate",
  "SubDAO",
  "Gnosis Safe",
  "Lido Finance",
  "Threshold Signature Schemes (TSS)"
];
function mulberry32(seed) {
  return function () {
    let t = (seed += 0x6d2b79f5);
    t = Math.imul(t ^ (t >>> 15), t | 1);
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

function pick(random, list) {
  return list[Math.floor(random() * list.length)];
}

function generateCambrianIdeas(seed =Date.now().toString()+Math.random(), count = 1) {
  console.log(seed)
  const rand = mulberry32(seed);
  const outputs = [];
  for (let i = 0; i < count; i++) {
    const idea = `${pick(rand, goals)}, ${pick(rand, targets)}, ${pick(rand, techs)}.`;
    outputs.push(idea);
  }

  return outputs.toString();
}
console.log(generateCambrianIdeas());
